language: go

go:
  - "1.11"

# skip install to grab dependencies from /vendor
install: true

# grab dynamodb local, gometalinter, minify and packr
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5
  - go get github.com/tdewolff/minify/cmd/minify
  - go get -u github.com/gobuffalo/packr/...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make lint
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=profile.cov ./...
  # remove testsuite.go coverage results from profile.cov -- seen as coveralls doesn't have a convenient way to do it
  - sed -i '/testsuite.go/d' ./profile.cov
  - goveralls -service=travis-ci -coverprofile=profile.cov || echo "Push to coveralls failed"

after_success:
  - make build
  - make prepare-aws
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  # Deploy to ap-southeast-2 cloudformation bucket
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: burner-kiwi-ap-southeast-2
    region: ap-southeast-2
    local_dir: build/cloudformation
  # Deploy to eu-west-1 cloudformation bucket
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: burner-kiwi-eu-west-1
    region: eu-west-1
    local_dir: build/cloudformation
  # Deploy to us-east-1 cloudformation bucket
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: burner-kiwi-us-east-1
    region: us-east-1
    local_dir: build/cloudformation
  # Deploy static assets
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: static.burner.kiwi
    region: ap-southeast-2
    local_dir: build/static
  # Deploy about.burner.kiwi assets
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: about.burner.kiwi
    region: ap-southeast-2
    local_dir: about.burner.kiwi
  # Deploy to lambda removed -- due to misuse
  # Deploy to dev specific branch
  # Deploy static assets to dev s3
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: dev-static.burner.kiwi
    region: ap-southeast-2
    local_dir: build/static
    on:
      branch: dev
  - provider: script
    script:  TAG=release-$(git rev-parse --short HEAD) make image-and-push && TAG=latest make image-and-push
