# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.0"

[[constraint]]
  name = "github.com/apex/gateway"
  version = "1.0.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.36"

[[constraint]]
  branch = "master"
  name = "github.com/bwmarrin/go-alone"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/justinas/alice"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
