apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:11.1
          resources:
            limits:
              memory: "250M"
              cpu: "0.25"
          ports:
            - containerPort: 5432
              name: service
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: psql-volume
          env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password    
      volumes:
        - name: psql-volume
          persistentVolumeClaim:
            claimName: psql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage