name: Quality Assurance
on: [push]
permissions:
  contents: write
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --skip-files [A-Za-z]*_test.go --enable misspell --enable gocyclo

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go mod download
      - run: make test
      - run: go test -covermode=count -coverprofile=profile.cov ./...
      - run: sed -i '/testsuite.go/d' ./profile.cov
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  release:
    name: Release
    needs:
      - test
      - golangci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: sudo apt-get install minify
      - run: echo "CUSTOM_CSS=styles.$(md5sum ./burner/static/styles.css | cut -c -32).min.css"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_CSS: ${{ env.CUSTOM_CSS }}
